# API Imports
from pybit import HTTP

# Config Variables
mode = 'test'
ticker1 = input('Ticker 1: ')
ticker2 = input('Ticker 2: ')
signal_positive_ticker = ticker2
signal_negative_ticker = ticker1
rounding_ticker1 = ...
rounding_ticker2 = ...
quantity_rounding_ticker1 = ...
quantity_rounding_ticker2 = ...